language: php
php: 
- 7.1.3

install:
- cp .env.travis env
- composer self-update
- composer install --no-interaction

script:
  - vendor/bin/phpunit
  
before_script:
  - php artisan migrate --force --seed

script:
- vendor/bin/phpcs
- vendor/bin/phpunit
  
deploy:
 provider: heroku
api_key:
  secure: KEY
app: martischool
on:
  repo: GeovannyMero/martischool
  branch: master
